### ISSUE TITLE
Which indicators can it measure?

### ISSUE THREAD

**Issue by wangjianyayaya** [bennyboer/quic-tcp-performance#1]
Can it be used to measure throughput, page load time, etc.?

**Comment by bennyboer** [comment]
Hi there!

Currently this is in very early development, so at the moment it is not able to measure anything.
The first goal is to measure throughput though. Give it another 2 - 3 weeks and it should be working!

**Comment by wangjianyayaya** [comment]
Looking forward to your work！

**Comment by bennyboer** [comment]
@wangjianyayaya The tool itself is now able to measure throughput. Although my tests are pretty strange. I also measured Page Load Times via E2E testing tool Selenium where I loaded youtube.com and google.com a bunch of times (> 100). My results show that for Page Load Times itself QUIC is faster when Cache is enabled in the Browser, otherwise TCP+TLS would be faster.

But back to throughput testing: It seems like the Go TCP implementation is faulty since it does not seem to scale the receive window properly, thus leading to strange results when RTT or packet loss is increased (where the receive window is not adjusted).
So when you use QUIC in the test and have high simulated RTT or packet loss, QUIC performs better, while TCP does not. But as said, it is due to the TCP Go implementation.
